config/routes.rb
Rails.application.routes.draw do
  mount ShopifyApp::Engine, at: 'home/index'
  devise_for :users, path: 'users', controllers: { sessions: "users/sessions",registrations: "users/registrations",  passwords: "users/passwords"}
  root :to=> 'dashboards#dashboard'

  resources :homes do
    collection do
      get :preferences
      get :reports
      get :receiving
      get :recvng
      get :recent
      get :posbills
      # get :orders_list
      get :bills
      get :bills_list

      get :recvform
      get :bill_forms
      get :home
      get :edit_user_form
      get :orders
      get :dashboard
    end
  end
  #dashboard routes
  resources :dashboards do
    collection do
      get :dashboard
    end
  end

  #sales people routes
  resources :sales_people do
    collection do
      get :all_sales_person
    end
  end

  #order_types_routes
  resources :order_types do
    collection do
      get :all_order_type
    end
  end

  #payment terms routes
  resource :payment_terms do
    collection do
      get :all_payment_term
    end
  end

  #product kit item 
  resources :kit_items do
    collection do 
      get :all_kit_item
    end
  end

  #order status routes
  resources :order_statuses do
    collection do
      get :all_order_status
    end
  end

  #order status routes
  resources :order_payment_modes do
    collection do
      get :get_order_payment_mode
    end
  end

  #Product track barcode
  resources :track_barcodes do 
    collection do
      get :all_track_barcode
    end
  end

  resources :orders do
    collection do
      get :check_product_availability
      get :orders_list
      get :orders_list_details
      get :get_order_types
      get :get_order_salespeople
      get :get_order_payment_terms
      get :get_order_statuses
      get :order_item_list
      get :get_product_list
      get :get_description_image
      get :get_customers
      get :get_order_scheduling
      get :barcode_search
      get :shopify_order_lists
      get :rental_picup_date
      get :item_calenders
      get :product_kind_category
    end
  end
  
  resources :vendors do
    collection do
      get :vendor_list
      get :get_vendor_types
      get :get_vendor_terms
      get :get_vendor_status
      get :get_vendor_document_types
      get :get_state
      get :get_city
    end
  end

  resources :vendor_types do 
    collection do 
      get :all_vendor_type
    end
  end

  resources :vendor_terms do 
    collection do 
      get :all_vendor_term
    end
  end

  resources :vendor_statuses do 
    collection do 
      get :all_vendor_status
    end
  end
  
  resources :customer_types do
    collection do
      get :all_customer_type
    end
  end

  resources :customer_terms do 
    collection do 
      get :all_customer_term
    end
  end

  resources :customer_sources do 
    collection do 
      get :all_customer_source
    end
  end

  resources :customer_shippings do 
    collection do 
      get :all_customer_shipping
    end
  end

  resources :customer_statuses do 
    collection do 
      get :all_customer_status
    end
  end

  resources :contact_method_types do 
    collection do 
      get :all_customer_contact_method_type
    end
  end

  resources :document_types do
    collection do
      get :all_customer_document_type
    end
  end

  resources :cities do
    collection do
      get :all_cities
    end
    member do 
      get :get_all_city_by_state
    end  
  end

  resources :customers do
    member do
      get :delete_customer
    end
    collection do
      get :customers_list
      get :get_customer_types
      get :get_customer_terms
      get :get_customer_sources
      get :get_customer_shippings
      get :get_customer_documents_types
      get :get_state
      get :get_city
      get :get_customer_status
      get :get_customer_method_types
      get :get_customer_addrs
      get :get_customer_new_addrs
      get :get_customer_ships
      get :get_customer_new_ships
    end
  end
  resources :products do
    collection do
      get :products_list
      get :shopify_product_lists
      get :get_product_types
      get :get_product_categories
      get :get_product_statuses
      get :get_product_item
      get :get_product_kit_item
      get :get_product_track_code
      get :get_product_kind_categories
      get :get_product_kind         
    end   
  end
  resources :product_types do 
    collection do 
      get :all_product_type
    end
  end

  resources :product_categories do 
    collection do 
      get :all_product_category
    end
  end

  resources :product_statuses do 
    collection do 
      get :all_product_status
    end
  end

  resources :homes
  
  resources :companies do
    collection do
      get :get_activity_types
      get :company_list
      get :get_state
      get :get_city
    end
  end

  resources :users do
    collection do
      get :user_list
      get :user_preference
      post :create_user_by_admin
    end
    member do 
      patch :edit_user_by_admin
    end
  end

  resources :activity_types do 
    collection do 
      get :all_activity_type
    end
  end
  
  resources :bills do
    member do
      get :get_genarate_bill
    end
    collection do
      get :bills_list
      get :get_bill_status
      get :get_vendors
    end
  end

  resources :bill_statuses do 
    collection do 
      get :all_bill_status
    end
  end

  resources :receivings do
    member do
      get :get_received_receipt
    end
    collection do
      get :receiving_list
      get :recent_inventory_list
      get :pos_bills_list
      get :product_received
      get :barcode_search_receiving
      # get :your_other_product_list
    end
  end
  
  resources :rental_settings do
    collection do
      get :add_rental_settings
    end
  end

  #user preference group
  resources :user_preference_groups do
  end
  # resources :vendor_list_vendors
end

app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :vendor, required: false
  belongs_to :order, required: false
  belongs_to :bill_status, required: false
  before_create :set_bill_number
  # validates :number, presence: true
  validates :date, presence: true
  # validates :vendor_term_id, presence: true
  # validates :bill_status_id, presence: true
  
  has_many :bill_notes, :dependent => :destroy
  accepts_nested_attributes_for :bill_notes, :allow_destroy => true
  
  def set_bill_number
    last_bill_number = Bill.maximum(:number)
    self.number = last_bill_number.to_i + 1  	
  end
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
	def bills_list
		@company_last = Company.last
	  @all_general_bills = Bill.all.paginate(:page => params[:page], :per_page => 7).order("created_at DESC")
	end
	def get_vendors
		puts "------------>> #{params[:vendor_id]}"
		val = params[:vendor_id]
		@vendor_address = Vendor.find(params[:vendor_id])
	    vendor_location = @vendor_address.vendor_locations.last
	    vendor_contact_method = @vendor_address.vendor_contact_methods.last
	    country_name = Country.find(vendor_location.country_id)
	    state_name = State.find(vendor_location.state_id)
	    city_name = City.find(vendor_location.city_id)
		render json: {:address=> vendor_location, :vendor=> vendor_contact_method, :country_name=> country_name, :state_name=> state_name, :city_name=> city_name}
	end
	def new
		@bill_status = BillStatus.new
		@general_bill = Bill.new
	  	@all_general_vendor = Vendor.all
    	@all_vendor_term = VendorTerm.all
	  	@all_general_bill_status = BillStatus.all
	  	@all_vendor_country = Country.all
		@all_vendor_state = State.all
    	@all_vendor_city = City.all
	  	@all_general_bills = Bill.last
	  if params[:number].present?
        @last_bill_number = Bill.where(number: number).last
      end
  end

	def get_genarate_bill
		@last_bill = Bill.find(params[:id])
		@company_last = Company.last
		respond_to do |format|
		  format.html
		  format.pdf do
		    render pdf: "get_genarate_bill", :page_size => 'A4'   # Excluding ".pdf" extension.
		  end
		end
	end

  def create
		@general_bill = Bill.new(params_general_bill)
		if @general_bill.save
			flash[:success] = "New Bill Created"
			redirect_to bill_path
		else
		puts "#{@general_bill.errors.full_messages.to_sentence}"
			flash[:error] = "New Bill Not created"
			redirect_to new_bill_path
		end
	end

	def edit
		@general_bill = Bill.find(params[:id])
		@all_general_vendor = Vendor.all
        @all_vendor_term = VendorTerm.all
	    @all_general_bill_status = BillStatus.all
	    @all_vendor_country = Country.all
		@all_vendor_state = State.all
    	@all_vendor_city = City.all
    	@all_general_bills = Bill.last
	end

	def show
		@bill_status = BillStatus.new
        @general_bill = Bill.find(params[:id])
		@all_general_vendor = Vendor.all
        @all_vendor_term = VendorTerm.all
	    @all_general_bill_status = BillStatus.all
	    @all_vendor_country = Country.all
		@all_vendor_state = State.all
    	@all_vendor_city = City.all
    	@all_general_bills = Bill.last
	end

	def destroy
		@general_bill = Bill.find(params[:id])
		if @general_bill.destroy
			flash[:success] = "Bill deleted"
			redirect_to bills_list_bills_path
			else
			flash[:error]	= "Bill not deleted"
			redirect_to bills_list_bills_path
		end
	end

	def update
  	@general_bill = Bill.find(params[:id])
  	if @general_bill.update_attributes(params_general_bill)
  	    if @general_bill.save
  	    	flash[:success] = "New Bill Update"
  			redirect_to bills_list_bills_path
  		else
  			puts "Error"
  			puts "=========>>>>   #{@general_bill.errors.full_messages.to_sentence}"
  	 		flash[:error] = "New Bill Not updated"
  			redirect_to  edit_bill_path
  	    end
  	end
	end
	def params_general_bill
		params.require(:bill).permit(:number, :date, :eta, :vendor_id, :vendor_term_id, :bill_status_id,bill_notes_attributes:[:note, :bill_id,:id,:_destroy])
	end	
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_bill_current_vendor_show.html.erb
<div class="content">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">
                    <label for="inputAddress 1">Address 1</label>
                    <input type="text" class="form-control" placeholder="Address 1" id="inputAddress1" disabled="disabled"/>
                </div>
                <div class="col-md-4">
                    <label for="inputType">Address 2</label>
                    <input type="text" class="form-control" placeholder="Address 2" id="inputAddress2" disabled="disabled"/>
                </div>
                <div class="col-md-4">
                    <label for="inputCountry">Country</label>
                    <input type="text" class="form-control" placeholder="Country Terms" id="inputCountry" disabled="disabled"/>
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">
                    <label for="inputCity">State</label>
                    <input type="text" class="form-control" placeholder="State" id="inputState" disabled="disabled"/>
                </div>
                <div class="col-md-4">
                    <label for="inputCountry Terms">City</label>
                    <input type="text" class="form-control" placeholder="City" id="inputCity" disabled="disabled"/>
                </div>
                <div class="col-md-4">
                    <label for="inputPhone">Phone</label>
                    <input type="text" class="form-control" placeholder="Phone" id="inputPhone" disabled="disabled"/>
                </div>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-4">
            <label for="inputPhone">Email</label>
            <input type="text" class="form-control" placeholder="Email" id="inputemail" disabled="disabled"/>
        </div>
    </div>
</div>

app/views/bills/_bill_items_form.html.erb
<div class="card mb-3">
    <div class="card-header">
        <i class="fa fa-money">&nbsp;</i>Bills</div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-light">
                    <tr>
                        <th>Codes</th>
                        <th>Items</th>
                        <th>Qty</th>
                        <th>Cost</th>
                        <th>Discount</th>
                        <th>Extra Cost</th>
                        <th>Tax</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>Tape</td>
                        <td>Gaffer Tape Black</td>
                        <td>2</td>
                        <td>$5000</td>
                        <td></td>
                        <td>$6000</td>
                        <td>
                            <input type="checkbox" name="vehicle" value="Car">
                            <br>
                        </td>

                    </tr>
                    <tr>
                        <td>Tape</td>
                        <td>Gaffer Tape Black</td>
                        <td>2</td>
                        <td>$5000</td>
                        <td></td>
                        <td>$6000</td>
                        <td>
                            <input type="checkbox" name="vehicle" value="Car" checked>
                            <br>
                        </td>
                    </tr>
                    <tr>
                        <td>Tape</td>
                        <td>Gaffer Tape Black</td>
                        <td>2</td>
                        <td>$5000</td>
                        <td></td>
                        <td>$6000</td>
                        <td>
                            <input type="checkbox" name="vehicle" value="Car" checked>
                            <br>
                        </td>
                    </tr>
                    <tr>
                        <td>Tape</td>
                        <td>Gaffer Tape Black</td>
                        <td>2</td>
                        <td>$5000</td>
                        <td></td>
                        <td>$6000</td>
                        <td>
                            <input type="checkbox" name="vehicle" value="Car" checked>
                            <br>
                        </td>
                    </tr>
                    <tr>
                        <td>Tape</td>
                        <td>Gaffer Tape Black</td>
                        <td>2</td>
                        <td>$5000</td>
                        <td></td>
                        <td>$6000</td>
                        <td>
                            <input type="checkbox" name="vehicle" value="Car" checked>
                            <br>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" class="blank"> </td>
                        <td colspan="3" class="total-line">Subtotal</td>
                        <td class="total-value">
                            <div id="subtotal">$875.00</div>
                        </td>
                    </tr>
                    <tr>

                        <td colspan="3" class="blank"> </td>
                        <td colspan="3" class="total-line">Total</td>
                        <td class="total-value">
                            <div id="total">$875.00</div>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" class="blank"> </td>
                        <td colspan="3" class="total-line">Amount Paid</td>

                        <td class="total-value">
                            <textarea id="paid">$0.00</textarea>
                        </td>
                    </tr>
                    <tr>
                        <td colspan="3" class="blank"> </td>
                        <td colspan="3" class="total-line balance">Balance Due</td>
                        <td class="total-value balance">
                            <div class="due">$875.00</div>
                        </td>
                    </tr>

                </tbody>
            </table>
        </div>
    </div>
</div>

app/views/bills/_bill_notes_form.html.erb
  <div class="row">
       <% @general_bill.bill_notes.build if @general_bill.bill_notes.blank?%>
      <div class="col-sm-12">
          <%= f.nested_fields_for :bill_notes do |ff|%>
              <div class="form-group">
                <%= ff.text_area :note, :class=>"form-control"%>
              </div>
              <div class="row">
        			<div class="col-sm-12 text-center">
        				<%= ff.submit "Save All", :class=>"btn btn-primary"%>
        			</div>
      		</div>
          <%end%>
      </div>
  </div>

app/views/bills/_bill_notes_new.html.erb
<div class="row">
    <!-- Order Tables -->
    <div class="col-md-12 col-xs-12">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-users companys-table-users-icon"></i>Bill Notes
                <button class="pull-right btn btn-primary table-print-icon"><i class="fa fa-print"></i></button>
                <button class="pull-right btn btn-primary table-download-icon"><i class="fa fa-download"></i></button>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="billNotes" width="100%" cellspacing="0">
                        <thead>
                            <tr class="info">
                                <th>Notes</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr class="info">
                                <th>Notes</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <%if @all_general_bills.present?%>
                                <%@all_general_bills.bill_notes.each do |x|%>
                                    <tr>
                                        <td><%=x.try(:note)%></td>
                                    </tr>
                                <%end%>
                               <%end%> 
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">UpCity/state/zipd yesterday at 11:59 PM</div>
        </div>
    </div>
</div>
<script type="text/javascript">
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('#billNotes').DataTable({
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]]
        });
    });
</script>

app/views/bills/_bill_notes_show_form.html.erb
  <div class="row">
       <% @general_bill.bill_notes.build if @general_bill.bill_notes.blank?%>
      <div class="col-sm-12">
          <%= f.nested_fields_for :bill_notes do |ff|%>
              <div class="form-group">
                <%= ff.text_area :note, :class=>"form-control edit-field", :readonly => true%>
              </div>
              <div class="row">
        		 <div class="col-sm-12">
            <div class="text-right">
            <%=link_to "Edit","javascript:void(0)",:class=>"btn btn-success edit_button"%>
                <%=ff.submit "Submit",:class=>"btn btn-info edit-btn"%>
            </div>
        </div>
      		</div>
          <%end%>
      </div>
  </div>
  <script type="text/javascript">
  $(document).on("turbolinks:load",function(){
    $(".edit_button").click(function(){
      //alert("hello");
      $(".edit-field").prop("readonly", false);
      $(".edit-field").prop("disabled", false);
    });
  });
</script>

app/views/bills/_bills_current_vendor_form.html.erb
<div class="content">
    <div class="col-sm-12">
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">
                    <label for="inputAddress 1">Address 1</label>
                    <span class="required_field">*</span>
                    <input type="text" class="form-control" placeholder="Address 1" id="inputAddress1" required="" />
                </div>
                <div class="col-md-4">
                    <label for="inputType">Address 2</label>
                    <input type="text" class="form-control" placeholder="Address 2" id="inputAddress2" />
                </div>
                <div class="col-md-4">
                    <label for="inputCountry">Country</label>
                    <span class="required_field">*</span>
                    <input type="text" class="form-control" placeholder="Country Terms" id="inputCountry"  required="" />
                </div>
            </div>
        </div>
    </div>
    <div class="col-sm-12">
        <div class="form-group">
            <div class="row">
                <div class="col-md-4">
                    <label for="inputCity">State</label>
                    <span class="required_field">*</span>
                    <input type="text" class="form-control" placeholder="State" id="inputState" required="" />
                </div>
                <div class="col-md-4">
                    <label for="inputCountry Terms">City</label>
                    <span class="required_field">*</span>
                    <input type="text" class="form-control" placeholder="City" id="inputCity" required="" />
                </div>
                <div class="col-md-4">
                    <label for="inputPhone">Phone</label>
                    <span class="required_field">*</span>
                    <input type="text" class="form-control" placeholder="Phone" id="inputPhone" required="" />
                </div>
            </div>
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-4">
                <label for="inputPhone">Email</label>
                <span class="required_field">*</span>
                <input type="text" class="form-control" placeholder="Email" id="inputemail" required="" />
            </div>
        </div>
</div>

app/views/bills/_bills_current_vendor_new.html.erb
<div class="row">
    <!-- Order Tables -->
    <div class="col-md-12 col-xs-12">
        <div class="card mb-3">
            <div class="card-header">
                <i class="fa fa-users companys-table-users-icon"></i>Current Vendor Info
                <button class="pull-right btn btn-primary table-print-icon"><i class="fa fa-print"></i></button>
                <button class="pull-right btn btn-primary table-download-icon"><i class="fa fa-download"></i></button>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered table-hover" id="billVendor" width="100%" cellspacing="0">
                        <thead>
                            <tr class="info">
                                <th>Address 1</th>
                                <th>Address 2</th>
                                <th>Country</th>
                                <th>state</th>
                                <th>City</th>
                                <th>Phone</th>
                                <th>Email</th>
                            </tr>
                        </thead>
                        <tfoot>
                            <tr class="info">
                                <th>Address 1</th>
                                <th>Address 2</th>
                                <th>Country</th>
                                <th>state</th>
                                <th>City</th>
                                <th>Phone</th>
                                <th>Email</th>
                            </tr>
                        </tfoot>
                        <tbody>
                            <%#if @all_general_company.present?%>
                                <tr>
                                    <td><%#=@all_general_company.try(:Address 1)%></td>
                                    <td><%#=@all_general_company.try(:Address 2)%></td>
                                    <td><%#=@all_general_company.City/state/zip.try(:Address 1)%></td>
                                    <td><%#=@all_general_company.Payment Terms.try(:Address 1)%></td>
                                    <td><%#=@all_general_company.Status.try(:Address 1)%></td>
                                </tr>
                            <%#end%>
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer small text-muted">UpCity/state/zipd yesterday at 11:59 PM</div>
        </div>
    </div>
</div>
<script type="text/javascript">
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('#billVendor').DataTable({
            "lengthMenu": [[5, 10, 25, 50, -1], [5, 10, 25, 50, "All"]]
        });
    });
</script>

app/views/bills/bills_list.html.erb
<div class="content-wrapper">
  <div class="container-fluid">
    <ol class="breadcrumb">
      <li class="breadcrumb-item">
        <a href="index.html">Dashboard</a>
      </li>
      <li class="breadcrumb-item active">Bills List</li>
<!--       <%#= link_to '/bills/new' do %>
        <button class="btn btn-primary btn-sm pull-right breadcrumb-button" data-toggle="" data-target="">Add New Bill</button>
      <%#end%> -->
    </ol>
    <div class="card mb-3">
      <div class="card-header">
        <i class="fa fa-money">&nbsp;</i>Bills
        <button class="pull-right btn btn-primary table-print-icon"><i class="fa fa-print"></i></button>
        <button class="pull-right btn btn-primary table-download-icon"><i class="fa fa-download"></i></button>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="" width="100%" cellspacing="0">
            <thead>
              <tr class="info">
                <th id="item-grid_c0">Sl.No.</th>
                <th id="item-grid_c1">Bill.no</th>
                <th id="item-grid_c2">Order ID</th>
                <th id="item-grid_c3">Order Date</th>
                <th id="item-grid_c4">Bill To</th>
                <th id="item-grid_c5">Ship Date</th>
                <th id="item-grid_c6">Invoice Date</th>
                <th id="item-grid_c7">Status</th>
                <th id="item-grid_c8">Total</th>
                <!-- <th id="item-grid_c9">Action</th> -->
                <th id="item-grid_c10">Bill PDF</th>
              </tr>
            </thead>
            <tbody>
              <%if @all_general_bills.present?%>
                <% @all_general_bills.each_with_index do |x, index|%>
                  <%
                    if (index + 1) % 2 == 0
                      class_name = "even"
                    else
                      class_name = "odd"
                    end
                  %>
                  <tr class="<%= class_name%>">
                    <td width="5%"><%=index+1%></td>
                    <td width="5%"><%= x.number%></td>
                    <td width="10%"><%= x.order.try(:number)%></td>
                    <td width="10%"><%= x.order.try(:date).strftime("%d-%b-%Y") if x.order.present?%></td>
                    <td width="20%">
                      <strong>Name : <%= x.order.order_bill_to.customer_location.try(:name) if x.order.order_bill_to.present? if x.order.present?%></strong><br>
                      <strong>Address : </strong><%= x.order.order_bill_to.customer_location.try(:address_line_1) if x.order.order_bill_to.present? if x.order.present?%><br>
                      <strong> Phone : </strong><%= x.order.order_bill_to.customer_location.try(:phone) if x.order.order_bill_to.present? if x.order.present?%> 
                    </td>
                    <td width="10%"><%= x.order.order_schedulings.last.try(:rental_picup).try(:strftime, '%d-%b-%Y') if x.order.present?%></td>
                    <td width="10%"><%= x.order.try(:date).try(:strftime, '%d-%b-%Y') if x.order.present?%></td>
                    <td width="10%"><%= x.order.order_status.try(:status)%></td>
                    <td width="10%" class="text-center">
                      <%if x.order.order_schedulings.present? %>
                        <%x.order.order_schedulings.each do |y|%>
                          <%@subtotal = get_total_ammount(y)%>
                        <%end%>
                        <%shipping_charge = @company_last.company_default.shipping_charge%>
                        <%tax_persion = @company_last.company_default.sales_tax_rate%>
                        <% sales_tax = sales_tax_report(@subtotal,tax_persion)%>
                        <%total_pay = @subtotal + shipping_charge + sales_tax%>
                        <strong> <%= total_pay%> </strong>
                      <%end%>
                    </td>
                    <td width="10%">
                      <a class="btn btn-danger" target="_blank" href="<%=get_genarate_bill_bill_path(x,format: :pdf)%>">Print as PDF <i class="fa fa-print"></i></a>
                    </td>
                  </tr>
                <%end%>  
              <%end%>  
            </tbody>
          </table>
          <%if @all_general_bills.count > 7%>
            <%if @all_general_bills.present?%>
              <div class="pager">      
                <%= will_paginate @all_general_bills, renderer: BootstrapPagination::Rails %>
              </div>
            <%end%>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>

<style type="text/css">
  td.odd {
    background: #eee !important;
  }
  td.even {
    background: #f9f9f9 !important;
  }
</style>

app/views/bills/edit.html.erb
<div class="content-wrapper">
    <div class="container-fluid">
        <ol class="breadcrumb">
            <li class="breadcrumb-item">
                <a href="/">Dashboard</a>
            </li>
            <li class="breadcrumb-item active"><a href="/bills/bills_list">Bills</a> 
            </li>
            <li class="breadcrumb-item active">
                Edit
            </li>
            <!--  <button class="btn btn-primary btn-sm pull-right breadcrumb-button">Add New Product</button> -->
        </ol>
        <%= render :partial => "bills/form_edit"%>
    </div>
</div>
<br>
<br>
<br>

<style type="text/css">
    .panel.with-nav-tabs .panel-heading {
        padding: 5px 5px 0 5px;
    }
    
    .panel.with-nav-tabs .nav-tabs {
        border-bottom: none;
    }
    
    .panel.with-nav-tabs .nav-justified {
        margin-bottom: -1px;
    }
    /*.products-general-info{
                min-height: 497px;
                max-height: 497px;
}
.products-barcodes{
                min-height: 300px;
                max-height: 300px;
}
.product-pricing{
                min-height: 229px;
                max-height: 229px;
}
.product-rental-cost{
                max-height: 199px;
                min-height: 199px;
}*/
</style>
<script type="text/javascript">
    // Call the dataTables jQuery plugin
    $(document).ready(function() {
        $('#dataTable').DataTable();
    });
</script>